### ISSUE TITLE
KeyError when runing the shell script to start training with the default parameters

### ISSUE THREAD

**Issue by zhaiyunfan** [mangelroman/audio2score#1]
When I follow each step you show on the instruction page, I try to use the command you give to reproduce and train my model, but I get the following error:
$ ./runtrain.sh config/quartets.cfg manifest_id model_id
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    model_name = config['train']['model']
  File "/home/zhaiyunfan/anaconda3/envs/a2s/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'train'

can you give me a hand?
Ubuntu 18.04.4 LTS
python 3.7

**Comment by zhaiyunfan** [comment]
I try to use 
$sudo ./runtrain.sh config/quartets.cfg manifest_id model_id
but the .sh script can't work 
I get a error:
./runtrain.sh: 1: ./runtrain.sh: [[: not found
./runtrain.sh: 10: ./runtrain.sh: python: not found

**Comment by mangelroman** [comment]
Hi there,
'sudo' should not be needed if you followed all the steps in the
Installation and Data section. Did you successfully run those previous
steps after installing miniconda?

The error you are getting is related to the quartets.cfg file not having a
particular header  named 'train'. Are you sure this file is present inside
config folder and contains the required information?

BR,
MA
